apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/xgboost-operator/manifests/overlays/kubeflow?ref=v0.2.0

images:
- name: kubeflow/xgboost-operator
  newName: kubeflow/xgboost-operator
  newTag: v0.2.0
