apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-applications/argocd.yaml
- argocd-applications/kubeflow-roles-and-namespaces.yaml
- argocd-applications/istio.yaml
- argocd-applications/dex-istio.yaml
- argocd-applications/profile-controller_access-management.yaml
- argocd-applications/central-dashboard.yaml
- argocd-applications/jupyter-web-app.yaml
- argocd-applications/notebook-controller.yaml
- argocd-applications/pipelines.yaml
- argocd-applications/pod-defaults.yaml
- argocd-applications/tensorboard-controller.yaml
- argocd-applications/tensorboards-web-app.yaml
- argocd-applications/volumes-web-app.yaml
