apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth

resources:
- github.com/kubeflow/manifests/common/dex/overlays/istio

images:
- name: quay.io/dexidp/dex
  newName: quay.io/dexidp/dex
  newTag: v2.22.0
