apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/mpi-operator/manifests/overlays/kubeflow

images:
- name: mpioperator/mpi-operator
  newName: mpioperator/mpi-operator
  newTag: latest
