apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=release-2.0
- argocd-cert.yaml
- argocd-ingress.yaml

patchesStrategicMerge:
- configmap-patch.yaml
