apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/davidspek/manifests/common/istio/oidc-authservice/base?ref=fix-oidc-manifest

images:
- name: gcr.io/arrikto/kubeflow/oidc-authservice
  newName: gcr.io/arrikto/kubeflow/oidc-authservice
  newTag: 28c59ef
