apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "HkPriYovYR2aXaD92eF51662kggd3a+3095XCdRTAmm4WeY7ZSWjruxstplE8Cin\nV86udhjbWeLaUpDMjmeGSGSAwPT10ii429AzC5jIQX7RfS4N/b+Vv87mN1cL1D28\nfdYpvmcZ13WiS6OVLJ3PozMm2KYNYFj5i47WYpBMyOk="
