apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/mxnet-operator/manifests/overlays/kubeflow?ref=v1.1.0

images:
- name: kubeflow/mxnet-operator
  newName: kubeflow/mxnet-operator
  newTag: v1.1.0
