apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/jetstack/cert-manager/releases/download/v1.2.0/cert-manager.yaml
- kubeflow-self-signing-issuer.yaml

images:
- name: quay.io/dexidp/dex
  newName: ghcr.io/dexidp/dex
  newTag: v2.28.1
